services:
  - type: web
    name: jardin-botanico-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

